// Generated by https://quicktype.io

export interface User {
  id: number
  first_name: string
  last_name: string
  username: string
  email: string
  avatar: string
  created: string
}

export interface UserDetail extends User {
  is_admin: boolean
  events: number[]
  events_liked: any[]
  events_created: number[]
}

export interface UserRegisterData {
  firstName: string
  lastName: string
  username: string
  emaik: string
  email: string
  password: string
  passwordConfirmed: string
}

export interface UserLogin {
  email: string
  password: string
}
