// Generated by https://quicktype.io
export interface SingleEvent {
  id: number
  title: string
  description: string
  cover?: string | null
  location: string
  attendees: number[]
  likes: number[]
  date_start: string
  date_end: string
  created_by: number
}

export interface SingleEventDetail extends SingleEvent {
  editor: number
  is_active: boolean
  created: string
  modified: string
}

export interface SingleEventUpdate {
  title?: string
  description?: string
  cover?: File | string
  attendees?: number[]
  likes?: number[]
  date_start?: string
  date_end?: string
}

export interface SingleEventCreate {
  title: string
  description: string
  cover?: File
  location: string
  date_start: string
  date_end: string
}

export interface SingleEventDates {
  date_start: string
  date_end: string
}
