// Generated by https://quicktype.io
import { User } from '@/apps/users/interfaces'

export interface SingleEvent {
  id: number
  title: string
  description: string
  cover: string | null
  location: string
  attendees: number[]
  likes: number[]
  date_start: string
  date_end: string
  created_by: number
}

export interface SingleEventDetail extends SingleEvent {
  editor: number
  is_active: boolean
  created: string
  modified: string
}

export interface SingleEventUpdate {
  title?: string
  description?: string
  cover?: string
  attendees?: number[]
  likes?: number[]
  date_start?: string
  date_end?: string
}
